//  CRIE UMA VARIAVEL PARA IDADE DE UMA PESSOA E EXIBA SE É MAIOR DE IDADE OU MENOR DE IDADE.

let idade=10; (" INFORME SUA IDADE, POR GENTILEZA !!")// CRIANDO UMA VARIAVEL LET IDADE PARA RECEBER A IDADE DO USER 

if ( idade < 18){ // USANDO IF E ELSE PARA VERIFICAR A CONDIÇÕES DA IDADE DO USER 
    console.log("VOCÊ É MENOR DE IDADE, POR GENTILEZA SE  RETIRE DO SITE") // MOSTRANDO O RESULTADO SE USER É MAIOR IDEADE 
}
else {
     
    console.log(" VOCÊ É MAIOR DE IDADE, SEJA BEM-VINDO AO SITE ") // MOSTRANDO O RESULTADO  SE USER É MENOR DE IDADE

}