// CRIE UMA VARIEVEL NÚMERICA E DIGA SE O NÚMERO É PAR OU (RESTO  DA DIVISÃO POR 2 = 0) ÍMPAR ( RESTO DA DIVISÃO POR 2=1 )

let num=24  // CRIANDO UMA VARIAVEL LET NUM PARA DECLARAR O VALOR 


if ( num %2 ==0){ // USANSO A FUNÇAO IF E ELSEPARA APLICAR A CONDIÇÃO SE É IMPAR OU PAR 
    console.log(" O NÚMERO ESCOLHIDO É PAR ----->" ) // MOSTRANDO O RESULTADO PAR 
}
else {
    console.log(" O NÚMERO ESCOLHIDO É ÍMPAR ---->") //MOSTRANDO O RESULTADO IMPAR 

}



 