//  CRIE UM PROGRAMA QUE RECEBA UM NÚMERO E EXIBA SUA TABUADA DE 1 A 10. 

let tabu = 1; // CRIANDO UMA VARIAVEL LET TABU QUE RECEBE VALOR , POR EXEMPLO 1
let num = 5; // CRIANDO UMA VARIAVEL LET NUM PARA RECEBER O VALOR, POR EXEMPLO 5
while (tabu <= 10) { // USANDO WHILE PARA APLICA A CONDIÇÃO DA TABUADA 
    console.log(` ${num} x ${tabu} = ${num * tabu} `);// MOSTRANDO O RESULTADO AO USER
    tabu++;
}
