//  CRIE UMA FUNÇÃO QUE RECEBA UM NÚMERO E RETORNE O DOBRO DELE JAVASCRIPT.

function dobrar(numero) { // CRIANDO A FUNÇÃO DOBRAR PARA RETORNA O DOBRO DO NÚMERO QUE O USER DIGITAR
	return numero * 2;
}