// CRIE UM PROGRAMA QUE EXIBA OS NÚMEROS DE  1 A 10 NO CONSOLE USANDO O "FOR"
 
for (let i=0; i<=10; i++) { //  USANDO FOR PARA EXIBIR OS  NÚMEROS DE 1 A 10 

console.log(i) // MOSTRANDO O RESULTADO DE 1 A 10 

}
 